/* CREATE AND GRANT PRIVILEGES TO USERS */
CREATE USER C##OLAP IDENTIFIED BY 1234;
GRANT CONNECT, DBA TO C##OLAP;

CREATE USER C##OLTP IDENTIFIED BY 1234;
GRANT CONNECT, DBA TO C##OLTP;

/* DELETE USERS */
DROP USER C##OLAP CASCADE;
DROP USER C##OLTP CASCADE;
