/* Tabela fato */
CREATE TABLE TB_VENDAS (
    ID_VENDAS INTEGER NOT null,
    ID_APARELHO INTEGER NOT null,
    ID_LOCAL INTEGER NOT null,
    ID_GENERO INTEGER NOT null,
    ID_TEMPO INTEGER NOT null,
    QUANTIDADE INTEGER NOT null,
    VALOR INTEGER NOT null
);

ALTER TABLE
    TB_VENDAS
ADD
    CONSTRAINT PK_VENDAS PRIMARY KEY (ID_VENDAS);

CREATE TABLE TB_LOCAL (
    ID_LOCAL INTEGER NOT null,
    ESTADO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL
);

ALTER TABLE
    TB_LOCAL
ADD
    CONSTRAINT PK_LOCAL PRIMARY KEY (ID_LOCAL);

CREATE TABLE TB_TEMPO (
    ID_TEMPO INTEGER NOT null,
    ANO INTEGER NOT null,
    QUADRIMESTRE INTEGER NOT null
);

ALTER TABLE
    TB_TEMPO
ADD
    CONSTRAINT PK_TEMPO PRIMARY KEY (ID_TEMPO);

CREATE TABLE TB_APARELHO (
    ID_Aparelho INTEGER NOT null,
    MODELO VARCHAR(100) NOT null,
    MARCA VARCHAR(100) NOT null
);

ALTER TABLE
    TB_APARELHO
ADD
    CONSTRAINT PK_APARELHO PRIMARY KEY (ID_APARELHO);

CREATE TABLE TB_GENERO(
    ID_GENERO INTEGER NOT null,
    GENERO VARCHAR(100) NOT null
);

ALTER TABLE
    TB_GENERO
ADD
    CONSTRAINT PK_ID_GENERO PRIMARY KEY (ID_GENERO);
