/*DROP CASO SEJA NECESSARIO*/ 
DROP TABLE IF EXISTS VENDAS;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS TEMPO;
DROP TABLE IF EXISTS LOCALIDADES;
DROP TABLE IF EXISTS APARELHOS;

/*TABLE DOS APARELHOS*/
CREATE TABLE APARELHOS (
    ID_APARELHO INTEGER NOT null CONSTRAINT UQ_ID_APARELHO UNIQUE,
    MODELO VARCHAR(100) NOT null,
    MARCA VARCHAR(100) NOT null,
    CONSTRAINT PK_APARELHO PRIMARY KEY (ID_APARELHO)
);

/*TABLE DA LOGRADURA SIMPLIFICADA*/
CREATE TABLE LOCALIDADES (
    ID_LOCAL INTEGER NOT null CONSTRAINT UQ_ID_LOCAL UNIQUE,
    ESTADO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_LOCAL PRIMARY KEY (ID_LOCAL)
);

/*TABLE DO TEMPO DA COMPRA*/
CREATE TABLE TEMPO (
    ID_TEMPO INTEGER NOT null CONSTRAINT UQ_ID_TEMPO UNIQUE,
    ANO INTEGER NOT null,
    QUADRIMESTRE INTEGER NOT null CONSTRAINT CHK_QUADRIMESTRE CHECK (QUADRIMESTRE BETWEEN 1 AND 3),
    CONSTRAINT PK_TEMPO PRIMARY KEY (ID_TEMPO)
);

/*TABELA DO GENERO DOS COMPRADORES*/
CREATE TABLE GENERO(
    ID_GENERO INTEGER NOT null CONSTRAINT UQ_ID_GENERO UNIQUE,
    GENERO VARCHAR(100) NOT null,
    CONSTRAINT PK_GENERO PRIMARY KEY (ID_GENERO)
);

/* TABLE FATO DO WH */
CREATE TABLE VENDAS (
    ID_VENDAS INTEGER NOT null CONSTRAINT UQ_ID_VENDAS UNIQUE,
    ID_APARELHO INTEGER NOT null,
    ID_LOCAL INTEGER NOT null,
    ID_GENERO INTEGER NOT null,
    ID_TEMPO INTEGER NOT null,
    QUANTIDADE INTEGER NOT null,
    VALOR DECIMAL NOT null,
    CONSTRAINT PK_VENDAS PRIMARY KEY (ID_VENDAS),
    CONSTRAINT FK_VENDAS_APARELHO FOREIGN KEY (ID_APARELHO) REFERENCES APARELHOS(ID_APARELHO),
    CONSTRAINT FK_VENDAS_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES LOCALIDADES(ID_LOCAL),
    CONSTRAINT FK_VENDAS_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
    CONSTRAINT FK_VENDAS_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO(ID_TEMPO)
);

<<<<<<< Updated upstream
ALTER TABLE
    TB_VENDAS
ADD
    CONSTRAINT PK_VENDAS PRIMARY KEY (ID_VENDAS);

CREATE TABLE TB_LOCAL (
    ID_LOCAL INTEGER NOT null,
    ESTADO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL
);

ALTER TABLE
    TB_LOCAL
ADD
    CONSTRAINT PK_LOCAL PRIMARY KEY (ID_LOCAL);

CREATE TABLE TB_TEMPO (
    ID_TEMPO INTEGER NOT null,
    ANO INTEGER NOT null,
    QUADRIMESTRE INTEGER NOT null
);

ALTER TABLE
    TB_TEMPO
ADD
    CONSTRAINT PK_TEMPO PRIMARY KEY (ID_TEMPO);

CREATE TABLE TB_APARELHO (
    ID_Aparelho INTEGER NOT null,
    MODELO VARCHAR(100) NOT null,
    MARCA VARCHAR(100) NOT null
);

ALTER TABLE
    TB_APARELHO
ADD
    CONSTRAINT PK_APARELHO PRIMARY KEY (ID_APARELHO);

CREATE TABLE TB_GENERO(
    ID_GENERO INTEGER NOT null,
    GENERO VARCHAR(100) NOT null
);

ALTER TABLE
    TB_GENERO
ADD
    CONSTRAINT PK_ID_GENERO PRIMARY KEY (ID_GENERO);
=======
>>>>>>> Stashed changes
