--LOCALIDADE
DECLARE
    CURSOR cur_Dados IS
        SELECT C.DESCRICAO CIDADE, E.DESCRICAO ESTADO 
        FROM C##OLTP.CIDADE C JOIN C##OLTP.ESTADO E ON c.id_cidade = e.id_estado;
    reg_Dados cur_Dados%ROWTYPE;
BEGIN
    OPEN cur_Dados;
    
    LOOP
        FETCH cur_Dados INTO reg_Dados;
        
        EXIT WHEN cur_Dados%NOTFOUND;
        
        INSERT INTO LOCALIDADE (ID_LOCAL, ESTADO, CIDADE)
        VALUES (SQ_LOCALIDADE.NEXTVAL, Reg_Dados.ESTADO, Reg_Dados.CIDADE);
    END LOOP;
    
    CLOSE cur_Dados;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

--APARELHO
DECLARE
    CURSOR cur_Dados IS
        SELECT M.DESCRICAO MODELO, MA.DESCRICAO MARCA 
        FROM C##OLTP.MODELO M JOIN C##OLTP.APARELHO ON m.id_modelo =  aparelho.id_aparelho JOIN C##OLTP.MARCA MA ON aparelho.id_aparelho = ma.id_marca;
    reg_Dados cur_Dados%ROWTYPE;
BEGIN
    OPEN cur_Dados;
    
    LOOP
        FETCH cur_Dados INTO reg_Dados;
        
        EXIT WHEN cur_Dados%NOTFOUND;
        
        INSERT INTO APARELHO (ID_APARELHO, MODELO, MARCA)
        VALUES (SQ_APARELHO.NEXTVAL, Reg_Dados.MODELO, Reg_Dados.MARCA);
    END LOOP;
    
    CLOSE cur_Dados;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

--GENERO
INSERT INTO GENERO (ID_GENERO, GENERO)
        VALUES (SQ_GENERO.NEXTVAL, 'F');
INSERT INTO GENERO (ID_GENERO, GENERO)
        VALUES (SQ_GENERO.NEXTVAL, 'M');

--TEMPO
DECLARE
    CURSOR cur_Dados IS
        SELECT DISTINCT
            EXTRACT(YEAR FROM C.DATA) AS ANO, 
            CASE 
                WHEN TO_CHAR(DATA, 'MM') IN ('01', '02', '03', '04') THEN 1
                WHEN TO_CHAR(DATA, 'MM') IN ('05', '06', '07', '08') THEN 2
                WHEN TO_CHAR(DATA, 'MM') IN ('09', '10', '11', '12') THEN 3
            END AS QUADRIMESTRE
        FROM C##OLTP.COMPRA C;
    reg_Dados cur_Dados%ROWTYPE;
    QUADRIMESTRE NUMBER;
BEGIN
    OPEN cur_Dados;
    
    LOOP
        FETCH cur_Dados INTO reg_Dados;
        
        EXIT WHEN cur_Dados%NOTFOUND;
        
        INSERT INTO TEMPO (ID_TEMPO, ANO, QUADRIMESTRE)
        VALUES (SQ_TEMPO.NEXTVAL, reg_Dados.ano, reg_Dados.QUADRIMESTRE);
    END LOOP;
    
    CLOSE cur_Dados;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

--VENDA
DECLARE
    CURSOR C_VENDA IS
        SELECT
            M.DESCRICAO AS MODELO,
            MA.DESCRICAO AS MARCA,
            CI.DESCRICAO AS CIDADE,
            ES.DESCRICAO AS ESTADO,
            CL.SEXO,
            CO.DATA,
            CA.QUANTIDADE,
            CA.VALOR
        FROM C##OLTP.APARELHO A
        JOIN C##OLTP.MODELO M ON A.ID_MODELO = M.ID_MODELO
        JOIN C##OLTP.MARCA MA ON M.ID_MARCA = MA.ID_MARCA
        JOIN C##OLTP.CARRINHO CA ON A.ID_APARELHO = CA.ID_APARELHO
        JOIN C##OLTP.COMPRA CO ON CA.ID_COMPRA = CO.ID_COMPRA
        JOIN C##OLTP.CLIENTE CL ON CO.ID_CLIENTE = CL.ID_CLIENTE
        JOIN C##OLTP.CIDADE CI ON CL.ID_CIDADE = CI.ID_CIDADE
        JOIN C##OLTP.ESTADO ES ON CI.ID_ESTADO = ES.ID_ESTADO;
        
    LINHA C_VENDA%ROWTYPE;
    CURRENT_ID_APARELHO NUMBER;
    CURRENT_ID_GENERO NUMBER;
    CURRENT_ID_TEMPO NUMBER;
    CURRENT_ID_LOCAL NUMBER;
    
BEGIN
    OPEN C_VENDA;
    
    LOOP
        FETCH C_VENDA INTO LINHA;
        EXIT WHEN C_VENDA%NOTFOUND;
        
        SELECT
            ID_APARELHO
        INTO CURRENT_ID_APARELHO
        FROM APARELHO
        WHERE LINHA.MODELO = APARELHO.MODELO AND LINHA.MARCA = APARELHO.MARCA;
        
        DBMS_OUTPUT.PUT_LINE('CURRENT_ID_APARELHO: ' || CURRENT_ID_APARELHO);
        
        /*
        INSERT INTO VENDA (ID_VENDA, ID_APARELHO, ID_LOCAL, ID_GENERO, ID_TEMPO, QUANTIDADE, VALOR)
        VALUES (SQ_VENDA.NEXTVAL, , );
        */
    
    END LOOP;
    
    CLOSE C_VENDA;

    -- COMMIT; 

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
    
END;